### ISSUE TITLE
დავალება 6 უკუკავშირი

### ISSUE THREAD

**Issue by TikoTs** [irakli427/sakhvadze_irakli#9]
სალამი ირაკლი, კარგი დავალება იყო. საბოლოო ჯამში შეფასება მაქსიმალური 1 ქულა.
1) Task 1 while attempt_counter <= 10: აქ ტოლობის ყოფნა ნიშნავს იმას,რომ გაქვს 11 ცდა ტოლობა ზედმეტია
2) Task 1ასევე attempt_counter შეგიძლია გაგეზარდა guess_number = int(input("what is your guess: ")) ის შემდეგ ერთგან და სამივე condition ში ცალ-ცალკე არ გაგეზარდა

**Comment by irakli427** [comment]
გასაგებია, მადლობაა
